name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Deno v1.x
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Publish package
        run: npx jsr publish
